copy .gitignore closeMainWin
copy .gitignore DesktopWidget
copy .gitignore drag
copy .gitignore drawBrush
copy .gitignore drawPen
copy .gitignore drawPoint
copy .gitignore EchoMode
copy .gitignore firstMainWin
copy .gitignore generator
copy .gitignore Icon_ToolsTip
copy .gitignore InceptionV3
copy .gitignore layout
copy .gitignore layoutWin
copy .gitignore lineEdit03
copy .gitignore lineEdit04
copy .gitignore lineEditMash
copy .gitignore MainWindow
copy .gitignore mnist
copy .gitignore nestLayout
copy .gitignore NumpyTorch
copy .gitignore PyCharm.Setup
copy .gitignore pyClass
copy .gitignore pyCtrl
copy .gitignore pyDef
copy .gitignore pyDic
copy .gitignore pyLambda
copy .gitignore pyList
copy .gitignore pymath
copy .gitignore pyPartial
copy .gitignore pyPrivateProperty
copy .gitignore pyProperty
copy .gitignore PyResource
copy .gitignore pyStr
copy .gitignore QButton
copy .gitignore QCalendar
copy .gitignore QCheckBox
copy .gitignore QClipboard
copy .gitignore QComboBox
copy .gitignore QDateTimeEdit
copy .gitignore QDialog
copy .gitignore QFileDialog
copy .gitignore QFontDialog
copy .gitignore QGridLayouot
copy .gitignore QInputDialog
copy .gitignore QLabel
copy .gitignore QLabel2
copy .gitignore QListView
copy .gitignore QListWidget
copy .gitignore QMenu
copy .gitignore QMessageBox
copy .gitignore QPrinter
copy .gitignore QRadio
copy .gitignore QSlider
copy .gitignore QSpinBox
copy .gitignore QSplitter
copy .gitignore QStatusBar
copy .gitignore QTableWidget
copy .gitignore QToolBar
copy .gitignore SignalSlot
copy .gitignore Spider
copy .gitignore TableViewModel
copy .gitignore tblMenu
copy .gitignore tbSelItem
copy .gitignore TestPyQt
copy .gitignore textEdit
copy .gitignore TorchNetwork
copy .gitignore torchTest
copy .gitignore widgetGeometry
